version: '3'

services:
  api:
    restart: always
    build:
      dockerfile: ./source/Dockerfile
    ports:
    - "9999:80"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dart_api
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
volumes:
  db_data: {}
